### ISSUE TITLE
Tasks error

### ISSUE THREAD

**Issue by baum-eule** [kurwjan/LanisAPI#16]
Wenn es einen Task/Eintrag gibt ohne Titel gibt es einen Crash.

File "***\Lib\site-packages\lanisapi\functions\tasks.py", line 67, in _get_tasks
    title = element.css_first("td:nth-child(2) > b:nth-child(1)").text()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by spezian** [comment]
Guck mal mit der neusten Version (0.3.0) ob es jetzt funktioniert.

**Comment by baum-eule** [comment]
Es funktioniert, wenn ich den "Mein Unterricht" Fehler behoben habe.
