### ISSUE TITLE
substitution error

### ISSUE THREAD

**Issue by baum-eule** [kurwjan/LanisAPI#17]
Wenn die Schule auf Lanis keinen Vertretungsplan hat gibt es einen "list index out of range" error. 
Vielleicht eine Prüfung auf Existenz einbauen. (Ich kann, wenn es gebraucht wird, auch die HTML schicken.)

  File "***\Lib\site-packages\lanisapi\functions\substitution.py", line 84, in _get_substitution_info
    date = re.findall(r"(\d\d\.\d\d\.\d\d\d\d)", html.html)[0]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by spezian** [comment]
Guck mal ob es mit der neusten Version (0.3.0) funktioniert, dort sollte auch die Prüfung auf Existenz eingebaut sein.

**Comment by baum-eule** [comment]
Danke die Prüfung funktioniert.

**Comment by spezian** [comment]
Super
