### ISSUE TITLE
Calendar Feature Idea

### ISSUE THREAD

**Issue by baum-eule** [kurwjan/LanisAPI#18]
Es wäre nützlich, wenn bei Kalendereinträgen auch steht von welchem Lehrer dieser erstellt wurde.
Dafür muss man den Wert von "Verantwortlich", der aus dem Json von Calendar kommt, mit der Lehrer ID verknüpfen.
An die IDs der Lehrer kommt man indem man alle Variationen von aa bis zz durchgeht. Dies wird bei der URL "https://start.schulportal.hessen.de/nachrichten.php?q={search}&page=1&a=searchRecipt" gemacht und gespeichert.

**Comment by spezian** [comment]
Wird auf jeden Fall hinzugefügt!

**Comment by spezian** [comment]
Ich glaube es ist besser, dass man die Mehr-Kalendardetails-Funktion von Lanis benutzt um denn Lehrernamen zu bekommen um Requests zu sparen, weil bei mir können manche Lehrer bis zu 4 Buchstaben haben und um sie am Ende zu bekommen hätte man Lanis zu bombadiert mit Requests und das darf man beim Web Scraping nicht vergessen, dahinter steckt noch immer ein Server.

Stattdessen zeigt man den Lehrernamen noch nicht direkt, sondern man gibt zuerst nur ein Callable zurück und beim aufrufen werden die Lehrernamen und andere Details zurückgegeben um somit Requests zu sparen. Lanis' Kalender Funktion dafür wäre ein ``POST-Request`` auf https://start.schulportal.hessen.de/kalender.php mit ``f: "getEvent"`` und ``id: Id des Events``.

Das gleiche muss ich auch bei den Nachrichten machen, da requeste ich jede einzelne Nachricht direkt um das Erstellungsdatum zu bekommen, was unsinnig ist.

Somit ist das ganze auch viel schneller, was eigentlich mein eigenes Ziel war.

**Comment by spezian** [comment]
Sollte nun mit Version 0.3.2 funktionieren.
