### ISSUE TITLE
_get_available_apps() bug

### ISSUE THREAD

**Issue by baum-eule** [kurwjan/LanisAPI#20]
Es wird "Mein Unterricht" nicht gefunden, weil es in implemented_apps "mein Unterricht" geschrieben wurde, aber dort  "Mein Unterricht" stehen muss. (Wenn es geändert wurde, wird MeinUntericht gefunden.)

**Comment by spezian** [comment]
Dann muss ich wohl nach ähnlichen Name suchen, weil bei mir heißt es aus irgendeinen Grund "*m*ein Unterricht"

**Comment by spezian** [comment]
Würde sagen ich vergleiche nicht nur die App-Namen in Lowercase sondern benutze irgendeinen Algorithmus um so viele verschiedene Namen wie möglich mitzukriegen

**Comment by baum-eule** [comment]
Ich denke es würde reichen, wenn es mit Lowercase behoben wird, weil es mit der gleichen URL funktioniert.

**Comment by spezian** [comment]
Es überprüft jetzt in Lowercase und nach starker Ähnlichkeit.
