### ISSUE TITLE
"Mein Unterricht" feature Idea

### ISSUE THREAD

**Issue by baum-eule** [kurwjan/LanisAPI#21]
Für jedes Unterrichtsfach gibt es auch eine Detaillierte Seite, die mehr Informationen besitzt. Diese Seite könnte man auch einbauen, um eine Historie anzuzeigen.
https://start.schulportal.hessen.de/meinunterricht.php?a=sus_view&id=1234

**Comment by spezian** [comment]
Gute Idee, würde diese Idee mit anderen Ideen bei #8 mergen.
