### ISSUE TITLE
No Substitution error ?

### ISSUE THREAD

**Issue by Vohwinkelh** [kurwjan/LanisAPI#31]
I ran the example code with my credentials and ended with this:

```
INFO - LanisClient   Authenticated.
INFO - httpx   HTTP Request: POST https://start.schulportal.hessen.de/vertretungsplan.php "HTTP/1.1 200 OK"
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File /opt/conda/lib/python3.11/site-packages/lanisapi/functions/substitution.py:88, in _get_substitution_info()
     87 try:
---> 88     date = re.findall(r"(\d\d\.\d\d\.\d\d\d\d)", date_element.text())[0]
     89 except AttributeError as err:

AttributeError: 'NoneType' object has no attribute 'text'

...

File /opt/conda/lib/python3.11/site-packages/lanisapi/functions/substitution.py:94, in _get_substitution_info()
     90     HTMLLogger.log_missing_element(
     91         html.html, "get_substitution_info()", "/", "date"
     92     )
     93     msg = "Critical date element was not found, something is definitely wrong! Please file a bug with the html_logs.txt file."
---> 94     raise CriticalElementWasNotFoundError(msg) from err
     96 LOGGER.info(f"Substitution info: Successfully got info. Notice is {bool(notice)}.")
     98 return {"notice": notice, "date": date}

CriticalElementWasNotFoundError: Critical date element was not found, something is definitely wrong! Please file a bug with the html_logs.txt file.
```

This is the actual conent of the page:

![image](https://github.com/kurwjan/LanisAPI/assets/61533897/94def623-d6b4-4d43-a730-07dd7c91539e)

I can see the text in the html_logs.txt

[html_logs.txt](https://github.com/kurwjan/LanisAPI/files/14229623/html_logs.txt)

Let me know what help can look like

**Comment by Vohwinkelh** [comment]
I spent some working through this. The main problem seems to be that there is no date on the page i am getting from the school and this case is not handled from the substitute.py

I added some crude handling as well as a classmethod empty. 

[substitution.txt](https://github.com/kurwjan/LanisAPI/files/14230006/substitution.txt)

I did not do proper testing on this, since it seems next week there is no subsitution

**Comment by spezian** [comment]
Oops I didn't notice this issue, unfortunately I am currently trying to rewrite this whole project but still thank you for the contribution. I'll handle this case in the rewrite.
