### ISSUE TITLE
zusätzlicher Tag

### ISSUE THREAD

**Issue by Vohwinkelh** [kurwjan/LanisAPI#33]
https://github.com/kurwjan/LanisAPI/blob/e39807b03c46318716999a15395c4d6f3f4116e3/src/lanisapi/functions/substitution.py#L129

lädt einen zusätzlichen Tag ... (unsere Schule hat immer 2 Tage einmal den aktuellen, dazu noch den nächsten Tag)

        # Add 1 day to the date
        tomorrow = date_obj + timedelta(days=1)

        # Create the list with the date and tomorrow
        date_list = [info["date"], tomorrow.strftime("%d.%m.%Y")]

        for date_str in date_list:
            print(f"Date: {date_str}")

            data = {"ganzerPlan": "true", "tag": date_str}

**Comment by spezian** [comment]
Sollte gelöst sein
