### ISSUE TITLE
⚡ - Add option to use (and get) school name and location to authenticate.

### ISSUE THREAD

**Issue by spezian** [kurwjan/LanisAPI#5]
Instead of 
```python
LanisClient("schoolid", ....)
```
You can use school name and location
```python
LanisClient("schoolname", "location")
```

When you authenticate for the first time it parses this [page](https://start.schulportal.hessen.de/) to get all schools. _(Probably in JSON format)_

Also add a function to get all schools for the developer.

**Comment by baum-eule** [comment]
Ich hatte mir mal was für ein eigenes Projekt Programmiert,
```
def search_school(school: str):
    import requests
    from bs4 import BeautifulSoup
    school = school.lower()
    r = []
    raw_text = requests.get("https://start.schulportal.hessen.de/").text
    soup = BeautifulSoup(raw_text, 'html.parser')
    item_list = soup.find_all("a", class_="list-group-item")
    for i in item_list:
        if school in i.text.lower():
            x = i.find("small").text
            r.append({
                "school": i.text.replace(" "+x, ""),
                "town": i.find("small").text,
                "id": i["data-id"]
                })
    return r
```
Vielleicht hilft es weiter.

**Comment by baum-eule** [comment]
Und es gibt diese Seite: https://startcache.schulportal.hessen.de/exporteur.php?a=schoollist

**Comment by spezian** [comment]
Hab auch diese Seite beim untersuchen gefunden und die next() funktion benutzt um die Schule zu finden.

**Comment by spezian** [comment]
Fixed with efa3f73d7e6f8a4d1b81a29b4b5df6d5568ed7fb
